[build]
  publish = "."

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/data/*.json"
  [headers.values]
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"
